### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by zzoher** [TheAlienDrew/OS-Scripts#1]
At C:\Tasks\Recreate-Base-Shortcuts.ps1:28 char:31
+     [Parameter(Mandatory=$true]
+                               ~
Missing closing ')' in expression.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:32 char:31
+     [Parameter(Mandatory=$true]
+                               ~
Missing closing ')' in expression.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:52 char:32
+   if ($sName -And $sTarget -And Test-Path $sTarget -PathType leaf) {
+                                ~
You must provide a value expression following the '-And' operator.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:52 char:33
+   if ($sName -And $sTarget -And Test-Path $sTarget -PathType leaf) {
+                                 ~~~~~~~~~
Unexpected token 'Test-Path' in expression or statement.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:52 char:33
+   if ($sName -And $sTarget -And Test-Path $sTarget -PathType leaf) {
+                                 ~~~~~~~~~
Missing closing ')' after expression in 'if' statement.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:23 char:28
+ function Recreate-Shortcut {
+                            ~
Missing closing '}' in statement block or type definition.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:52 char:66
+   if ($sName -And $sTarget -And Test-Path $sTarget -PathType leaf) {
+                                                                  ~
Unexpected token ')' in expression or statement.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:85 char:5
+   } else if (-Not ($sName -Or $sTarget)) {
+     ~~~~
Unexpected token 'else' in expression or statement.
At C:\Tasks\Recreate-Base-Shortcuts.ps1:98 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndParenthesisInExpression

**Comment by TheAlienDrew** [comment]
All that should be fixed now, since the following changes:
- https://github.com/TheAlienDrew/OS-Scripts/commit/aec56e1b0c483e791d9ed6a89c82f14940a3c853
- https://github.com/TheAlienDrew/OS-Scripts/commit/b1f01153ed4a0b88a0e9cc5bd65ac9b11c388a66
- https://github.com/TheAlienDrew/OS-Scripts/commit/4cf1c53bdd415a3feb416884e7fe767cceab19b9
- https://github.com/TheAlienDrew/OS-Scripts/commit/902f385064163ac49db0645b2ce08affde4be99a
