### ISSUE TITLE
[Add App] Recreate-Base-Shortcuts.ps1 - Autodesk Software

### ISSUE THREAD

**Issue by tdebuhr** [TheAlienDrew/OS-Scripts#15]
Looking to get AutoDesk apps added, such as AutoCad, Inventor and Revit.. 

here are the Paths to the install locations.. 
- **AutoCad 2023** - `C:\Program Files\Autodesk\AutoCAD 2023\acad.exe`
- **Inventor 2023** - `C:\Program Files\Autodesk\Inventor 2023\Bin\Inventor.exe`
- **Revit 2023** - `C:\Program Files\Autodesk\Revit 2022\Revit.exe`

let me know if that is what you need or if you need something else.. If I can get this added it will keep our Engineering Lab teachers from hunting me down :) 

Thank you

**Comment by TheAlienDrew** [comment]
I'll make sure to add those first, when I have the time, then I'll go after some of their other applications, as I'm sure others will mention them.

**Comment by tdebuhr** [comment]
Thank you... It's nice that there is someone way smarter than anyone at Microsoft can help clean up the messes they make..

Trevor DeBuhr
Application Support Coordinator
Nampa School District Technology Center
1002 Front Street
Nampa, ID 83651
***@***.******@***.***>
Phone: 208-468-4769
VoIP ext. 1109

**Comment by TheAlienDrew** [comment]
I've never even used AutoDesk, but I already hate it...
![image](https://user-images.githubusercontent.com/19640692/213900211-604be6d0-7755-40a3-8398-fc8d9ae7e599.png)

**Comment by TheAlienDrew** [comment]
@tdebuhr they should be added now, since commit: https://github.com/TheAlienDrew/OS-Scripts/commit/8db9a69233f79578487f05ecdbba0c01e7d176c4
