### ISSUE TITLE
New App - "Remote Desktop" 

### ISSUE THREAD

**Issue by AlphaSeb** [TheAlienDrew/OS-Scripts#18]
Awesome script you build! I noticed that this important app is missing:

Could you add "C:\Program Files\Remote Desktop\msrdcw.exe" "Remote Desktop" for Azure Virtual Desktop?

**Comment by TheAlienDrew** [comment]
Added in commit: https://github.com/TheAlienDrew/OS-Scripts/commit/c896f45473f2b635bbb92e9e86008ae71afbc9b1
