### ISSUE TITLE
[Add App] Recreate-Base-Shortcuts.ps1 - WizTree

### ISSUE THREAD

**Issue by bartlaarhoven** [TheAlienDrew/OS-Scripts#24]
I would like to have WizTree added, it's found on https://diskanalyzer.com/ and puts itself in `C:\Program Files\WizTree\` (you have `WizTree.exe` and `WizTree64.exe` there)

**Comment by TheAlienDrew** [comment]
Added via commit https://github.com/TheAlienDrew/OS-Scripts/commit/357c690dcc15186cc4c6f388adeba572c91956eb
