### ISSUE TITLE
[Bug] Recreate-Base-Shortcuts-INTUNE.ps1- Cannot overwrite variable REMOTE_SCRIPT_LOCATION

### ISSUE THREAD

**Issue by AlphaSeb** [TheAlienDrew/OS-Scripts#25]
Running the Intune Script with SYSTEM Rights, in 64 Bit Shell results into the following:

eNotWritable,Microsoft.PowerShell.Commands.SetVariableCommand
 
Set-Variable : Cannot overwrite variable REMOTE_SCRIPT_LOCATION because it is read-only or constant.
At line:92 char:1
+ Set-Variable REMOTE_SCRIPT_LOCATION -Option Constant -Value "https:// ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (REMOTE_SCRIPT_LOCATION:String) [Set-Variable], SessionStateUnauthorizedAcce 
   ssException
    + FullyQualifiedErrorId : VariableNotWritable,Microsoft.PowerShell.Commands.SetVariableCommand
 
Set-Variable : Cannot overwrite variable REMOTE_SCRIPT_LOCATION because it is read-only or constant.
At line:92 char:1
+ Set-Variable REMOTE_SCRIPT_LOCATION -Option Constant -Value "https:// ...

![image](https://user-images.githubusercontent.com/16120414/214841244-aba4e1e3-008b-48b4-afd6-ade76344283c.png)

**Comment by TheAlienDrew** [comment]
Well if you run it more than once, that error is bound to happen, but I've added some code that ignores the error if it is to occur in the latest commit: https://github.com/TheAlienDrew/OS-Scripts/commit/2bcd1c313f24be452c73d45f73a275b1ace3e955

**Comment by TheAlienDrew** [comment]
Actual issue was figured out and fixed in https://github.com/TheAlienDrew/OS-Scripts/commit/68eb71dbe852758f535df03934dff580dec766a4 ... try to latest version of the intune script.
