### ISSUE TITLE
[Add App] Recreate-Startmenu-Shortcuts.ps1 - SAP Logon

### ISSUE THREAD

**Issue by thekristoffer01** [TheAlienDrew/OS-Scripts#26]
hello 
can also add **SAP Logon** `C:\Program Files (x86)\SAP\FrontEnd\SapGui\saplogon.exe`

**Comment by TheAlienDrew** [comment]
@thekristoffer01 could you copy the shortcuts related to the program from a computer that wasn't affected, and zip/upload them here?

**Comment by thekristoffer01** [comment]
hello 
i have also added the directory if needed 
see also added saplogon.txt file just rename it to .exe then works 

 Directory of C:\Program Files (x86)\SAP\FrontEnd\SapGui

26.01.2023  09:32    <DIR>          .
24.01.2023  15:40    <DIR>          ..
24.01.2023  15:40    <DIR>          ab4_data
14.04.2022  05:06         1 165 488 abpgui.dll
14.04.2022  05:06         1 466 032 ag7as.dll
14.04.2022  05:08           102 064 apodpgrid.ocx
14.04.2022  05:08           490 152 apogrid.ocx
14.04.2022  05:08           235 184 apoviewer.ocx
14.04.2022  05:06         1 738 416 AssignmentCtrl.dll
24.01.2023  15:40    <DIR>          bitmap
13.04.2022  16:28         2 239 304 chart.ocx
14.04.2022  05:08            79 536 combobox.ocx
27.11.2018  02:00                40 compInfo760.txt
14.04.2022  05:06           618 160 convlib.dll
24.01.2023  15:40    <DIR>          dat
17.07.2018  14:42         1 030 144 dbghelp.dll
14.04.2022  05:06           447 152 eCATTRH.dll
14.04.2022  05:06            93 360 eumfcdll.dll
27.09.2018  14:26             9 488 euspd1ld
27.09.2018  14:26             7 036 euspd1le
27.09.2018  14:26             1 701 euspd2ld
27.09.2018  14:26             1 552 euspd2le
27.09.2018  14:26             3 428 euspd3ld
27.09.2018  14:26             2 648 euspd3le
27.09.2018  14:26             3 403 euspd4ld
27.09.2018  14:26             3 110 euspd4le
27.09.2018  14:26             5 910 euspd5ld
27.09.2018  14:26             5 409 euspd5le
27.09.2018  14:26           108 278 euspddld
27.09.2018  14:26            10 026 euspddle
27.09.2018  14:26               473 euspetld
27.09.2018  14:26               473 euspetle
27.09.2018  14:26           115 016 euspicld
27.09.2018  14:26            55 113 euspicle
27.09.2018  14:26               879 euspkeyw
27.09.2018  14:26               220 euspktld
27.09.2018  14:26               190 euspktle
27.09.2018  14:26             5 392 eusplsld
27.09.2018  14:26             4 753 eusplsle
27.09.2018  14:26               555 euspptld
27.09.2018  14:26               555 euspptle
27.09.2018  14:26           123 210 euspstld
27.09.2018  14:26           123 065 euspstle
27.09.2018  14:26            60 995 euspsxld
27.09.2018  14:26            61 346 euspsxle
27.09.2018  14:26            11 763 euspumld
27.09.2018  14:26            10 341 euspumle
14.04.2022  05:09         2 300 080 FrontOptEdit.exe
14.04.2022  05:09           477 360 gnbax.exe
14.04.2022  05:09           105 648 gnbmx.exe
14.04.2022  05:09           217 776 gnbux.exe
14.04.2022  05:09            66 224 gndlx.exe
14.04.2022  05:09            46 768 gnetx.exe
14.04.2022  05:09         3 914 928 gneux.exe
14.04.2022  05:09           197 296 gngax.exe
14.04.2022  05:07           210 608 gngmb.dll
14.04.2022  05:09           201 392 gnhix.exe
14.04.2022  05:09           141 488 gnhox.exe
14.04.2022  05:09            98 992 gnhpx.exe
14.04.2022  05:09            70 832 gnmsx.exe
14.04.2022  05:09           353 456 gnnex.exe
14.04.2022  05:09           127 152 gnpox.exe
14.04.2022  05:09            82 096 gnscx.exe
14.04.2022  05:09           199 344 gnstx.exe
14.04.2022  05:09           378 544 gnsux.exe
14.04.2022  05:09            67 248 gnupx.exe
14.04.2022  05:09            63 152 gnwdx.exe
14.04.2022  05:07           660 656 gnwie.dll
14.04.2022  05:09            64 176 gnxlx.exe
13.04.2022  16:28           479 048 grctrl.ocx
14.04.2022  05:08           926 896 GridView.ocx
13.04.2022  16:28            63 816 Grnfmt32.dll
13.04.2022  16:28           466 248 GRVISGDI.DLL
13.04.2022  16:46             9 311 GuiAbapBits.xml
14.04.2022  05:07         4 061 360 guirfc.dll
13.04.2022  16:46         7 287 056 guixt.dll
13.04.2022  16:46         2 145 552 guixt.exe
18.02.2019  07:50            40 776 help_04.exe
24.01.2023  15:41    <DIR>          htmlhelp
13.04.2022  16:28         1 166 664 ICDataFlow.ocx
17.07.2018  14:35               483 ICDataFlow.ocx.uninstall.reg
13.04.2022  16:28         1 089 352 ICJoin.ocx
17.07.2018  14:35               568 ICJoin.ocx.uninstall.reg
14.04.2022  05:07           448 176 landscape_migration.dll
26.01.2023  09:32    <DIR>          Lang
14.04.2022  05:08           327 344 listcontrol.ocx
14.04.2022  05:08           327 344 listcontrolchild.ocx
14.04.2022  05:07         1 976 496 lprintg.dll
14.04.2022  05:07           140 464 LSAPIWrapper.dll
14.04.2022  05:10            60 080 minizip.dll
14.04.2022  05:09         1 501 360 niping.exe
14.04.2022  05:09            48 816 omsprint.exe
14.04.2022  05:08            59 056 PersonasGridview.ocx
14.04.2022  05:08            53 424 PersonasImage.ocx
14.04.2022  05:07           316 144 PsDebug.dll
14.04.2022  05:07           144 112 PsErrorDbg.dll
14.04.2022  05:07           370 352 rndrtlib.dll
14.04.2022  05:08         1 099 440 sapab4edit.ocx
14.04.2022  05:07           191 152 sapab4lex.dll
14.04.2022  05:07         3 468 464 sapalvstub.dll
14.04.2022  05:07            76 976 SAPawole.dll
14.04.2022  05:07            79 024 SAPawrfc.dll
14.04.2022  05:08           665 264 SAPbarc.OCX
14.04.2022  05:07           235 696 sapborderpainter.dll
14.04.2022  05:07           301 744 SAPBTFEditor.dll
14.04.2022  05:08           561 328 sapcalen.ocx
14.04.2022  05:08           707 248 sapcltfc.ocx
14.04.2022  05:09            62 640 sapcms.exe
14.04.2022  05:08           395 952 SAPcncli.OCX
14.04.2022  05:08           401 584 SAPcncsv.OCX
14.04.2022  05:08           111 280 sapcombo.ocx
14.04.2022  05:07         2 072 752 sapcomni.dll
14.04.2022  05:07            33 456 SapControlPluginInvoker.dll
14.04.2022  05:08           515 760 sapdatap.ocx
14.04.2022  05:07         2 289 840 sapdpams.dll
14.04.2022  05:08           153 776 sapdpcts.ocx
14.04.2022  05:08           283 824 SAPEDIT.OCX
14.04.2022  05:07           311 472 sapfctrl.dll
14.04.2022  05:07           208 560 sapfdraw.dll
14.04.2022  05:07           653 488 SAPfesec.dll
14.04.2022  05:07            54 448 SAPfewcb.dll
14.04.2022  05:07           140 464 SAPfewcls.dll
14.04.2022  05:07           344 752 sapfewcmen.dll
14.04.2022  05:07           795 312 SAPfewcx.dll
14.04.2022  05:07         3 737 776 sapfewdbg.dll
14.04.2022  05:07           754 352 SAPfewdp.dll
14.04.2022  05:07            34 992 sapfewdp_proxy.dll
14.04.2022  05:07           112 304 SAPfewdr.dll
14.04.2022  05:07            55 984 SAPfewed.dll
14.04.2022  05:08           552 624 SAPfewin.OCX
14.04.2022  05:06            99 504 sapfewinFL.dll
14.04.2022  05:07            90 288 SAPfewnls.dll
14.04.2022  05:07           144 560 sapfewrm.dll
14.04.2022  05:08         1 564 848 sapfewse.ocx
14.04.2022  05:07            96 432 SAPfewtr.dll
14.04.2022  05:07         3 242 672 SAPfewui.dll
14.04.2022  05:07            54 448 sapfewuimsg.dll
14.04.2022  05:07           346 800 SAPfewut.dll
14.04.2022  05:07            37 552 sapfhook.dll
14.04.2022  05:07           171 696 sapfilecache.dll
14.04.2022  05:07           344 240 sapformpainter.dll
14.04.2022  05:07           474 288 sapfprint.dll
14.04.2022  05:07         5 161 648 SAPfront.dll
14.04.2022  05:09         3 223 728 SAPftp.exe
14.04.2022  05:08           254 640 sapgradp.ocx
14.04.2022  05:09           127 152 SAPgui.exe
14.04.2022  05:09           179 888 SAPGUIControlPlugin.exe
14.04.2022  05:07         1 383 600 sapguidrw32.dll
14.04.2022  05:07            84 656 SapGuiFocus.dll
24.01.2023  15:41    <DIR>          SAPguihelp
14.04.2022  05:07         2 269 872 SAPguilib.dll
14.04.2022  05:08        12 303 536 SAPguiRM.ocx
14.04.2022  05:07        12 952 752 sapguirm32.dll
14.04.2022  05:09           318 640 SapGuiServer.exe
14.04.2022  05:08           423 600 SAPguisv.ocx
14.04.2022  05:08           681 648 SAPHTML.OCX
14.04.2022  05:08           103 088 SAPHTMLM.OCX
14.04.2022  05:07            79 024 SAPHTMLP.DLL
14.04.2022  05:09         3 573 424 SAPhttp.exe
14.04.2022  05:08            98 992 SAPilidr.ocx
14.04.2022  05:07           241 328 SAPImage.dll
14.04.2022  05:07           286 896 saplgdll.dll
14.04.2022  05:07           269 488 saplgmgr.dll
14.04.2022  05:07           399 536 saplgmgr2.dll
14.04.2022  05:07            36 016 saplgmgr_proxy.dll
14.04.2022  05:07           591 024 saplgnui.dll
14.04.2022  05:09         2 571 440 saplgpad.exe
14.04.2022  05:09         1 677 488 saplogon.exe
14.04.2022  05:08         1 005 232 sapmap.ocx
14.04.2022  05:07            59 568 SAPmemmgt.dll
14.04.2022  05:07           111 280 sapmime.dll
14.04.2022  05:08           480 944 SAPnetz.OCX
14.04.2022  05:07         5 706 928 sapnwrfccm.dll
14.04.2022  05:08           427 184 SAPoimgr.OCX
14.04.2022  05:08           566 448 SAPoipd.OCX
14.04.2022  05:08         2 035 376 SAPoipe8.OCX
14.04.2022  05:08         2 094 768 SAPoipss.OCX
14.04.2022  05:08         1 211 568 SAPoipw8.OCX
14.04.2022  05:07         6 156 976 SAPpcfvd.dll
14.04.2022  05:07           196 272 SAPpctxt.dll
14.04.2022  05:08            44 208 sappdfpr.dll
14.04.2022  05:08           115 376 SapPersonasResourceManager.dll
14.04.2022  05:08            86 704 SAPROTWR.DLL
13.04.2022  16:46            48 356 SAPrules.xml
14.04.2022  05:08            49 840 SAPsbar.OCX
14.04.2022  05:08         1 191 088 SAPsdcc.OCX
14.04.2022  05:08           135 856 SAPsel.OCX
14.04.2022  05:08         2 929 328 sapsettings.ocx
14.04.2022  05:09           142 512 sapsettingsshow.exe
14.04.2022  05:09           401 584 sapshcut.exe
14.04.2022  05:08         2 784 432 sapshlib.dll
14.04.2022  01:46           173 056 sapsign.ocx
14.04.2022  05:08           142 512 sapsplit.ocx
14.04.2022  05:08           177 840 sapstage.ocx
14.04.2022  05:08           253 104 SAPTABCN.OCX
14.04.2022  05:08           449 200 saptablepainter.dll
14.04.2022  05:08           107 184 saptbar.ocx
14.04.2022  05:08           107 696 sapthmdrw.dll
14.04.2022  05:08           654 000 saptoolb.dll
14.04.2022  05:08           258 224 SAPUILandscape.ocx
14.04.2022  05:08         3 314 352 sapwdtaocx.ocx
14.04.2022  05:08           307 888 sapwin.dll
14.04.2022  05:08           491 184 sapwnt.dll
24.01.2023  15:41    <DIR>          Scripting
24.01.2023  15:40    <DIR>          Sounds
14.04.2022  03:01         1 071 715 sqlite3.dll
14.04.2022  05:09         2 827 440 ssfrfc.exe
27.11.2018  20:43             1 081 ssfrfc.ini
17.07.2018  14:42           359 424 symsrv.dll
14.04.2022  05:08           267 952 TestFixtures.dll
14.04.2022  05:08           375 984 textedit.dll
24.01.2023  15:40    <DIR>          themes
24.01.2023  15:41    <DIR>          Unicode
13.04.2022  16:45           759 208 vcprct32.dll
13.04.2022  16:45         3 693 456 vcsced32.dll
13.04.2022  16:45         4 742 960 vcwin32.dll
14.04.2022  05:08           155 824 WCRContainer.dll
14.04.2022  05:09           104 624 wdbdadpt.ocx
14.04.2022  05:09           151 216 wdbdadptjoin.ocx
14.04.2022  05:09           500 912 wdobapi.ocx
14.04.2022  05:09           523 952 WDTAOCX.OCX
14.04.2022  05:09           513 200 wdtfuncs.ocx
14.04.2022  05:09         1 027 760 WDTMCTRL.OCX
14.04.2022  05:09           153 776 wdtmlgnd.ocx
14.04.2022  05:09           151 216 WDTRMENU.OCX
14.04.2022  05:09         1 266 864 WDTTREE.OCX
26.01.2023  09:33    <DIR>          wwi
14.04.2022  05:10           149 680 zlibwapi.dll
24.01.2023  15:40                 0 __sap.dir
             216 File(s)    174 637 346 bytes
[saplogon.txt](https://github.com/TheAlienDrew/OS-Scripts/files/10928926/saplogon.txt)

**Comment by thekristoffer01** [comment]
[SAP Logon.zip](https://github.com/TheAlienDrew/OS-Scripts/files/10931045/SAP.Logon.zip)
oky lets try again 🤣🤣

**Comment by TheAlienDrew** [comment]
It should be added now.
