### ISSUE TITLE
[Add App] Recreate-Base-Shortcuts.ps1

### ISSUE THREAD

**Issue by CJHarms** [TheAlienDrew/OS-Scripts#4]
Cisco Jabber

Path: C:\Program Files (x86)\Cisco Systems\Cisco Jabber\
Filename: CiscoJabber.exe

**Comment by TheAlienDrew** [comment]
Added in commit: https://github.com/TheAlienDrew/OS-Scripts/commit/e9d4482502d3bf701d0fb20a0b9cc1a6446d6d06
