### ISSUE TITLE
MethodInvocationException

### ISSUE THREAD

**Issue by duffman0** [TheAlienDrew/OS-Scripts#5]
I seem to get MethodInvocationException on every detected shortcut. The script runs successfully and creates the shortcuts as expected, but the errors thrown make the script report as failed when deployed via Intune:

Script logs:

`Microsoft Edge
WARNING: Target invalid! Doesn't exist or is spelled wrong:
C:\Program Files\Microsoft\Edge\Application\msedge.exe

Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7
+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files (x86)\Microsoft Intune Management
Extension\Policies\Scripts\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7
+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Microsoft Edge
Created shortcut at:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft Edge.lnk

Microsoft Intune Management Extension
WARNING: Target invalid! Doesn't exist or is spelled wrong:
C:\Program Files\Microsoft Intune Management Extension\AgentExecutor.exe

Microsoft Intune Management Extension
A shortcut already exists at:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft Intune Management Extension\Microsoft Intune Management Extension.lnk

Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7
+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files (x86)\Microsoft Intune Management
Extension\Policies\Scripts\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7
+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Access
Created shortcut at:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Access.lnk

Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7
+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files (x86)\Microsoft Intune Management
Extension\Policies\Scripts\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7
+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
`

IntuneManagementExtension logs:

`<![LOG[[PowerShell] Fail, the details are {"Version":1,"SigningCode":649,"SigningMsg":"(Success) AccountId:81bc032c-14e5-4216-acbd-78f4b5e3f9f5,PolicyId:d8abbb42-7cfc-4615-9ba7-050962608636,Type:1,Enforce: Enforcement2. OSVersion:10.0.22621,AgentVersion:1.61.156.0. ","ExecutionMsg":"Exception calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference not set to an instance of an object.\"\r\nAt C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\0543cd33-9783-479f-b2c0-6a48e6f6c49d_d8abbb42-7cfc-4615-9ba7-050962608636.ps1:116 char:7\r\n+       [Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | O ...\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : NullReferenceException\r\n \r\nException calling \"ReleaseComObject\" with \"1\" argument(s): \"Object reference	 	01/01/1601 00:00:00	2867984480 (0xAAF1F860)
`

**Comment by TheAlienDrew** [comment]
Fixed in commit https://github.com/TheAlienDrew/OS-Scripts/commit/b1cc52161828c9e0ff480837bc5632a7b426aac2
